### ISSUE TITLE
Turkish Letters

### ISSUE THREAD

**Issue by xlegendryx** [alias-rahil/lyrics-finder#3]
Turkish letters are not supported, can you fix this. thank you

**Comment by alias-rahil** [comment]
Should be fixed in [this](https://github.com/alias-rahil/lyrics-finder/commit/d0230087f936224d71fc89c3a119431a3ad3528e) commit.

If not:

Can you post the output/screenshot?

**Comment by xlegendryx** [comment]
Thank you 👍

**Comment by alias-rahil** [comment]
:)
