### ISSUE TITLE
Finding almost no lyrics.

### ISSUE THREAD

**Issue by ABotDev** [alias-rahil/lyrics-finder#4]
if you search it on google you find the lyrics. but if u try to use it with a bot nope no lyrics found

**Comment by alias-rahil** [comment]
Can you specify a song name? It would be helpful for me to solve the issue.

**Comment by ABotDev** [comment]
Desiigner - Panda

**Comment by alias-rahil** [comment]
It works for me. Just tried it on [runkit](https://npm.runkit.com/lyrics-finder/).

```
const lyricsFinder = require("lyrics-finder");
console.log(lyricsFinder("Desiigner - Panda", ""));
```

**Comment by ABotDev** [comment]
![Screenshot_20200811-144322_Discord.jpg](https://user-images.githubusercontent.com/66113328/89898440-08346f00-dbe1-11ea-9504-19abdc1c9e6f.jpg)

**Comment by alias-rahil** [comment]
Have you integrated the package correctly? I am afraid i am gonna have to close this issue as there is no problem with the package.
