### ISSUE TITLE
Request Blocked?

### ISSUE THREAD

**Issue by hiteshsatwani** [alias-rahil/lyrics-finder#9]
Everytime i make a request using JS i get this response

Access to fetch at 'https://www.google.com/search?q=Mood%20Swings%20(feat.%20Lil%20Tjay)%20Pop%20Smoke' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Any idea how i can fix this?

**Comment by alias-rahil** [comment]
Try this:
```
fetch('https://www.google.com/search?q=Mood%20Swings%20(feat.%20Lil%20Tjay)%20Pop%20Smoke', { mode: 'no-cors'})
```

**Comment by hiteshsatwani** [comment]
aight ok thanks!

**Comment by hiteshsatwani** [comment]
ok a quick update the requests are now going through but the response is completely empty.

![image](https://user-images.githubusercontent.com/37097855/99906984-97c6df00-2cf3-11eb-9227-46eb2f0fb71c.png)
![image](https://user-images.githubusercontent.com/37097855/99906987-9e555680-2cf3-11eb-8d2d-4d10e8106e6a.png)

**Comment by hiteshsatwani** [comment]
this is for all 4 requests
